sudo: required
language: javascript
before_install:
- openssl aes-256-cbc -K $encrypted_502e7d9c4880_key -iv $encrypted_502e7d9c4880_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
script:
  echo "No script"
after_success:
- ssh-keyscan -t rsa -H 137.74.197.11 >> ~/.ssh/known_hosts
- ssh root@137.74.197.11 'bash -s' < serverdeploy.sh
