env:
  global:
  - secure: iFFYacflGw6ixL4nbe49uAWZZdlnRWsE3aKQhprZwTAKLlYn9tyI7XG+5ea+yxBOLg4G++y0AIXpOuIJw9Wl2od5WgVPSR4NcEkb7F1/+RVaOnvtCipUWlUVCKAqi0SpnuzqGtTcd4U/fvTN85WW9zTkYFoF/uJAyhqWo7BRr0ww+7HWeaKzcps1giJuLIae3ExpQ/K1tSKWULxqhtdN71ICDfmJludHBVbUqcidtrA2ZoIOW1Dx/6LC0a3WTgmbZ2p4akrv+1phxreMHSvzBnnSIrqFkc+Dn90jYk/WGqsstzR2rsFv1ZoZJJWPQPEE2v9VHFVuX9tmsJwWH0GEZOiGhI5yOg0Fi4ahJ2ckeIryzFAYS/IDcnJ1vHsmUZ7KH2y8Gciqdq90brkjvCP6e7yY4fKeC7xOzJLkeDG6CQ61ecNyr7BDSt/pLEXV8OwsGahBzKJ9Z6l8KifFSVsxdryDtgT+ZWkSmcn6OGo5P1IyB44f46Px362M9c5T40nlAKgDzIfH1ISm6OOIlL5zebH6r2GSza6I8sjf7wV0ShO+9yVBUkwueDkvQqwrYpv27KwD6N3PcdCHae+kFaEBodcAGl79L6fOIPgLEbiuSLsGauR44cqoBFAhbolB4HTVgKLdNk0SKCYo+mYx5oIR0ixflSkE2xvlTi1utUcugak=
  - secure: znv7rc3+FAgJabIOX03/8tvC0AaZ5dOT5LS1QBLYvKLFIc2mceD3VSZBaK3ltNKq17bvUX8KjRb/AZT63NVS0qvKl4vaXY2lBXGR62pAHTK5z3+4nZBa5TGrtVlAufYD5HEsaZFUYwzolZ1XOL4ZZYrIdM79WH10E+808oawnoztueMFB60BmfQ35Le9BFibowN0aUGA7Flh0QMnZ35Ac6d8hb8Qn6pLwrBSdX95UwFFlfVMGQNLmpabVFIh0BY+KfU9Yr/jer8egrDat68/iRcJLg8w4aXKlKmPejHkg7E0QI1vQw4fOLPYedby1hUJjOOIxC2shSpCEzuxW0Kn0z5WjEh0zAaVbWkP6AbMF8aGtmIJ4L64y2U0Xsa1Uie/0jZvSK92tpVSUH1Yl2yJojmeUA8PLYvpVS6WBDzv/ZWBncy9P865giDFuaCyQP+nRhJ9dDA9x5aJPYpMtGKpRuGInfMXuEexvzN6LRIzB2cZ0Tp7RUvuNA71teJGyxJFEIAq/IAwkAU4kRyX0VqshMktqPJBMJRhXztCuItGt/MkIbYBPq9/htTH8DAGq3FMjXdcorld5+2bP7NweMAdMnE8ehN1PQm4AmcmHOLyfRFW1KIDsBXnTE08oHV/YWDFWQSQhBn7nHhJAeySP5DxfUCB7q0aetTxqq52HLxxhSI=
  - secure: ChBObIfNKGCZ0Ohl1GGOhZjeqrsRFlnu6ei3ANgsbuR8Arn8JogZ9boZBmlYy9iMX1y95K0rk0WuOoNVn2ZvPYcJiR8sjT+2n0QnvCWOyJh4WbKVLmlioJ8X1WiCAkiHmC4l3j9e+5O455Fs9RcEKs6fhxV9Us6W6yFDiF3GBt0kweb1D3H5YaEUyoATpA1uo9fAC2qgImbXflz2b/J78Jm63m5bNmnMJMFU/aofkDHpWdo6Ote4tpH9MszeOrKLRpGL87t7M/x3O2xhRdZWDJDGghxe7Xjy2l5QFLOpMLOPMx4IDR2TffjQXMWBYXO9j0rjHzVjCnLSTY4konLRzmp6Upiz5jOkPLTMbikRksgBxqrlumCRJgYEGs4IfrLQS5QXEGsCmjrbZmpOQd3fIDmUPFftKu8bhvOArdItINMWyfUUwO9iHmb+CtYuKutK3PlTifAgr3HDZe/KsYMbRTAbpDSB1TRDUiUL0zli8IXqlJOmjb2+91wAx+tSc4B0A4LH9yu712g2tamGo2PDv8QpjfACtjpTYBHvrbMSrMcEMrmbPTUoZyjVoqsTVh38zGBKT2cc1J17daXGgpngLTOyADAlmlej+5K+MlXu3N4IEnTXtFOvBJvgny1Ste3s3VafNeyUgchCbe4R+AS1UogFc322kRTYaZqRluiKqjU=
sudo: required
language: javascript
before_install:
- openssl aes-256-cbc -K $encrypted_f60c42f4bee3_key -iv $encrypted_f60c42f4bee3_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- echo "Installing nothing."
script:
- docker build -t pezula .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag pezula ramon54321/pezula
- docker push ramon54321/pezula
- ssh-keyscan -t rsa -H 137.74.197.11 >> ~/.ssh/known_hosts
- ssh root@137.74.197.11 sh ./script.sh
